### PR TITLE
Migrate to Chef::ServerAPI

### PR DESCRIPTION
**Pull request by RAR**
## Pull Request Checklist

In reference to: https://github.com/sensu-plugins/sensu-plugins-chef/issues/16

#### Purpose

Remove use of deprecated Chef::REST.

### CODE REVIEW

**Comment by astrauka** [comment]
@mattyjones could you please review this commit? Looking forward to using it

**Comment by astrauka** [comment]
@eheydrick could you please review this PR? Looking forward to using it

**Comment by sstarcher** [comment]
From `chef-api` ChefAPI is currently in rapid development! You should not consider this API stable until the official 1.0.0 release.

**Comment by majormoses** [comment]
echoing the same sentiment as above: https://github.com/sensu-plugins/sensu-plugins-chef/issues/16#issuecomment-275706774

**Comment by majormoses** [comment]
I would say that ridley is a more appropriate move until `Chef::ServerAPI` is 1.0

**Comment by RAR** [comment]
That makes sense.  I'll close this - I'm switching to another job that's not using Chef so hopefully someone else can pick this up with 1.0 is reached and everything is a bit more stable.

**Pull request closed without merging**
