### PR TITLE
Check if a chef node exists or not

### PR DESCRIPTION
**Pull request by obazoud**

### CODE REVIEW

**Comment by eheydrick** [comment]
Thanks @obazoud! Tests are failing on Ruby 1.9.3 due to an upstream dependency of ridley requiring ruby > 2.0.0. We need to either drop ruby 1.9.3 or use a different chef API client that works with 1.9.3. Considering that 1.9.3 is EOL I'd be in favor of dropping 1.9.3 support.

**Comment by obazoud** [comment]
Well my PR does not change gemspec.

**Comment by obazoud** [comment]
@eheydrick fixed :)

**Comment by analytically** [comment]
Can you add this to the README and add an entry in the changelog?

**Comment by obazoud** [comment]
@analytically done

**Comment by analytically** [comment]
In release 0.0.5. Thanks!

**Pull request merged**
