### PR TITLE
fixes #16 uninstialized constant in chef >= 12.7

### LINKED ISSUE #16: check-chef-nodes fails to run: uninitialized constant Chef::REST
Chef server and Sensu server have both been working in prod for a few months. Tried this chef plugin today and got error below

EX CMD:
`sudo /opt/sensu/embedded/bin/ruby ./check-chef-nodes.rb -U https://<MY_HOSNAME>/organizations/<ORG> -K /etc/chef/<MY_VALIDATOR>.pem`

ERROR:

> Check failed to run: uninitialized constant Chef::REST, ["./check-chef-nodes.rb:99:in `chef_api_connection'", "./check-chef-nodes.rb:69:in`connection'", "./check-chef-nodes.rb:73:in `nodes_last_seen'", "./check-chef-nodes.rb:103:in`any_node_stuck?'", "./check-chef-nodes.rb:86:in `run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:in`block in class:CLI'"]

check-chef-server.rb plugin script seems to work fine, however.

### PR DESCRIPTION
**Pull request by majormoses**
## Pull Request Checklist

fixes #16 

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
Temporary workaround before rewriting in ridley to get past:
```
Check failed to run: uninitialized constant Chef::REST, ["./check-chef-nodes.rb:99:in chef_api_connection'", "./check-chef-nodes.rb:69:inconnection'", "./check-chef-nodes.rb:73:in nodes_last_seen'", "./check-chef-nodes.rb:103:inany_node_stuck?'", "./check-chef-nodes.rb:86:in run'", "/opt/sensu/embedded/lib/ruby/gems/2.2.0/gems/sensu-plugin-1.2.0/lib/sensu-plugin/cli.rb:56:inblock in class:CLI'"]
```

### CODE REVIEW

**Comment by majormoses** [comment]
Long term wise we need to rewrite in Ridley but that's a separate matter. We should fix for currently broken clients.

**Comment by majormoses** [comment]
@cwjohnston can we get this merged? there are a fair amount of broken people and this immediately unblocks them (including me).

**Comment by cwjohnston** [comment]
Released in 2.0.1 now available on RubyGems.

**Comment by majormoses** [comment]
@cwjohnston thank you.

**Pull request merged**
